### PR TITLE
:bug: avoid cluster auto approve failed occasionally

### LINKED ISSUE #386: cluster auto approve could fail occasionally
**Describe the bug**
When enable the AutoApprove feature gate, sometimes the cluster will not be get accepted by the hub due to timing issue.

**To Reproduce**
enable the AutoApprove feature gate with `clusteradmin init` and run `clusteradm join`.  It happens occasionally.

**Expected behavior**
The cluster should be always approved

**Environment ie: OCM version, Kubernetes version and provider:**
latest

**Additional context**

### PR DESCRIPTION
**Pull request by skeeey**
## Summary
Remove the accept cluster logic from the CSR controller, and put them in the managed cluster controller  

## Related issue(s)

Fixes #386

### CODE REVIEW

File: pkg/registration/hub/csr/reconciler.go [hunk 1]
```diff
@@ -129,24 +137,25 @@ func (b *csrBootstrapReconciler) Reconcile(ctx context.Context, csr csrInfo, app
 		return reconcileContinue, nil
 	}
 
-	err := b.accpetCluster(ctx, clusterName)
+	err := b.acceptCluster(ctx, clusterName)
```
Comment (nirs) [inline pkg/registration/hub/csr/reconciler.go:140]: Mixing typos fixes with a real change make it harder to review and make it hard to maintain the code later. If you revert this fix because it caused a regression, we will lose also the typo fixes.

File: pkg/registration/hub/csr/reconciler.go [hunk 2]
```diff
@@ -129,24 +137,25 @@ func (b *csrBootstrapReconciler) Reconcile(ctx context.Context, csr csrInfo, app
...
 	if errors.IsNotFound(err) {
-		// Current spoke cluster not found, could have been deleted, do nothing.
-		return reconcileStop, nil
+		// Current spoke cluster not found, it may not be created yet, requeue it until we cannot find its related CSR
+		b.eventRecorder.Warningf("ManagedClusterNotApproved", "spoke cluster %q is not found", clusterName)
+		return reconcileRequeue, nil
```
Comment (nirs) [inline pkg/registration/hub/csr/reconciler.go:144]: So if we have a CSR but we cannot find the managed cluster we queue the request and will check again after some delay?

I expect that if this reconciler depends on a CSR and ManagedCluster, it will watch both resources. If the ManagedCluster is missing, you can do nothing, and once the ManagedCluster appears, you can approve the CSR.

File: pkg/registration/hub/csr/reconciler.go [hunk 3]
```diff
@@ -129,24 +137,25 @@ func (b *csrBootstrapReconciler) Reconcile(ctx context.Context, csr csrInfo, app
 		return reconcileContinue, nil
 	}
 
-	err := b.accpetCluster(ctx, clusterName)
+	err := b.acceptCluster(ctx, clusterName)
 	if errors.IsNotFound(err) {
-		// Current spoke cluster not found, could have been deleted, do nothing.
-		return reconcileStop, nil
+		// Current spoke cluster not found, it may not be created yet, requeue it until we cannot find its related CSR
+		b.eventRecorder.Warningf("ManagedClusterNotApproved", "spoke cluster %q is not found", clusterName)
```
Comment (nirs) [inline pkg/registration/hub/csr/reconciler.go:143]: This warning will be useful!

File: pkg/registration/hub/csr/reconciler.go [hunk 4]
```diff
@@ -129,24 +137,25 @@ func (b *csrBootstrapReconciler) Reconcile(ctx context.Context, csr csrInfo, app
...
-		return reconcileContinue, err
+		return reconcileRequeue, err
 	}
 
 	b.eventRecorder.Eventf("ManagedClusterAutoApproved", "spoke cluster %q is auto approved.", clusterName)
 	return reconcileStop, nil
 }
 
-func (b *csrBootstrapReconciler) accpetCluster(ctx context.Context, managedClusterName string) error {
+func (b *csrBootstrapReconciler) acceptCluster(ctx context.Context, managedClusterName string) error {
```
Comment (nirs) [inline pkg/registration/hub/csr/reconciler.go:158]: Another typo that should not be part of this fix.

**Review by nirs — COMMENTED** [review]
How can I test this fix?

File: pkg/registration/hub/csr/reconciler.go (hunk 1 above)
Comment (skeeey) [reply pkg/registration/hub/csr/reconciler.go:140]: good suggestion, I will drop the typos fixes in this pr

File: pkg/registration/hub/csr/reconciler.go (hunk 2 above)
Comment (skeeey) [reply pkg/registration/hub/csr/reconciler.go:144]: I will use a separated controller to handle cluster, and make this csr controller only handle the CSR ,  this will be more clear

**Comment by skeeey** [comment]
> How can I test this fix?

If you want to test with this pr, you can use my pr's repo to build your own images, then use `clusteradm init --image-registry` to specify the images

File: pkg/registration/hub/managedcluster/controller.go [hunk 5]
```diff
@@ -103,6 +110,15 @@ func (c *managedClusterController) sync(ctx context.Context, syncCtx factory.Syn
 	}
 
 	if !managedCluster.Spec.HubAcceptsClient {
+		// If the ManagedClusterAutoApproval feature is enabled, we automatically accept this cluster and
+		// add an annotation to mark its initial join as accepted.
```
Comment (nirs) [inline pkg/registration/hub/managedcluster/controller.go:114]: The comment does is not clear about the purpose of the annotation.

Based on the new test, we want to approve the cluster once on the first time we discover it, so the cluster admin can deny the cluster. This should be explained in the comment.

File: pkg/registration/hub/managedcluster/controller.go [hunk 6]
```diff
@@ -199,3 +215,11 @@ func (c *managedClusterController) removeManagedClusterResources(ctx context.Con
 	}
 	return operatorhelpers.NewMultiLineAggregate(errs)
 }
+
+func (c *managedClusterController) acceptCluster(ctx context.Context, managedClusterName string) error {
+	// TODO support patching both annotations and spec simultaneously in the patcher
+	patch := fmt.Sprintf("{\"metadata\":{\"annotations\":{\"%s\":\"\"}},\"spec\":{\"hubAcceptsClient\":true}}", initialJoinAcceptedAnnotationKey)
```
Comment (nirs) [inline pkg/registration/hub/managedcluster/controller.go:221]: This works but hard to read and error prone. Maybe use a raw string literal to avoid the extra \" escapes?

    patch := fmt.Sprintf(`{"metadata":{"annotations":{"%s":""}},"spec":{"hubAcceptsClient":true}}`)

We don't have a value for the annotation so we use an empty string - maybe we can add a timestamp as the value to have more context? or the name of the controller adding this annotation? This can make it easier to debug issues.

File: test/integration/registration/spokecluster_autoapproval_test.go [hunk 7]
```diff
@@ -88,4 +94,58 @@ var _ = ginkgo.Describe("Cluster Auto Approval", func() {
...
+		}, v1.CreateOptions{})
+		gomega.Expect(err).NotTo(gomega.HaveOccurred())
+
+		gomega.Eventually(func() error {
+			cluster, err := util.GetManagedCluster(clusterClient, clusterName)
+			if err != nil {
+				return err
+			}
+
+			if _, ok := cluster.Annotations["open-cluster-management.io/initial-join-accepted"]; !ok {
```
Comment (nirs) [inline test/integration/registration/spokecluster_autoapproval_test.go:113]: Based on this test, it seems that the purpose of the annotation is to approve the cluster automatically only once, so if the cluster is denied manually it will not approved automatically again. So the annotation can be renamed to "automatically-approved".

File: pkg/registration/hub/managedcluster/controller.go [hunk 8]
```diff
@@ -103,6 +110,15 @@ func (c *managedClusterController) sync(ctx context.Context, syncCtx factory.Syn
 	}
 
 	if !managedCluster.Spec.HubAcceptsClient {
+		// If the ManagedClusterAutoApproval feature is enabled, we automatically accept this cluster and
+		// add an annotation to mark its initial join as accepted.
+		if features.HubMutableFeatureGate.Enabled(ocmfeature.ManagedClusterAutoApproval) {
+			// Only accept this cluster upon its initial join.
```
Comment (nirs) [inline pkg/registration/hub/managedcluster/controller.go:116]: This comment is not needed, the comment above can explain the cases we want to handle.

**Review by nirs — COMMENTED** [review]
If I understand this change correctly, the only task the managedCluster controller need to do is to set hubAcceptsClient to true once?

The CSR approval is not related to this and will work correctly even if the CSR is found before the managed cluster is created?

**Comment by skeeey** [comment]
> If I understand this change correctly, the only task the managedCluster controller need to do is to set hubAcceptsClient to true once?
you are correct, the managedCluster controller only set  hubAcceptsClient to true once

> The CSR approval is not related to this and will work correctly even if the CSR is found before the managed cluster is created?
yes, with this, the CSR approval process and managed cluster accept process will be independent

File: pkg/registration/hub/managedcluster/controller.go (hunk 6 above)
Comment (skeeey) [reply pkg/registration/hub/managedcluster/controller.go:221]: agree, I think a timestamp may be more help

File: test/integration/registration/spokecluster_autoapproval_test.go (hunk 7 above)
Comment (skeeey) [reply test/integration/registration/spokecluster_autoapproval_test.go:113]: may be used this annotation
`open-cluster-management.io/automaticlly-accpected-by-managedclusterctrl=<the accept timestamp>`

File: pkg/registration/hub/managedcluster/controller.go (hunk 5 above)
Comment (skeeey) [reply pkg/registration/hub/managedcluster/controller.go:114]: I will update this make it more clear

File: pkg/registration/hub/managedcluster/controller.go (hunk 8 above)
Comment (skeeey) [reply pkg/registration/hub/managedcluster/controller.go]: removed

File: pkg/registration/hub/managedcluster/controller.go [hunk 9]
```diff
@@ -20,14 +22,18 @@ import (
...
 	"open-cluster-management.io/sdk-go/pkg/patcher"
 
 	"open-cluster-management.io/ocm/pkg/common/apply"
 	"open-cluster-management.io/ocm/pkg/common/queue"
+	"open-cluster-management.io/ocm/pkg/features"
 	"open-cluster-management.io/ocm/pkg/registration/helpers"
 	"open-cluster-management.io/ocm/pkg/registration/hub/manifests"
 )
 
+const clusterAcceptedAnnotationKey = "open-cluster-management.io/automatically-accepted-by-managedclusterctrl"
```
[the remark this answers is not in the document]
Comment (skeeey) [reply pkg/registration/hub/managedcluster/controller.go:35]: yeah, let's go with "automatically-accepted-on" and timestamp firstly

**Review by nirs — APPROVED** [review]

**Comment by nirs** [comment]
I tested the latest version, 250 deploys succeeded.

File: pkg/registration/hub/managedcluster/controller.go [hunk 10]
```diff
@@ -20,14 +22,18 @@ import (
...
 	"open-cluster-management.io/sdk-go/pkg/patcher"
 
 	"open-cluster-management.io/ocm/pkg/common/apply"
 	"open-cluster-management.io/ocm/pkg/common/queue"
+	"open-cluster-management.io/ocm/pkg/features"
 	"open-cluster-management.io/ocm/pkg/registration/helpers"
 	"open-cluster-management.io/ocm/pkg/registration/hub/manifests"
 )
 
+const clusterAcceptedAnnotationKey = "open-cluster-management.io/automatically-accepted-on"
```
[the remark this answers is not in the document]
Comment (skeeey) [reply pkg/registration/hub/managedcluster/controller.go:37]: added
